/*!-----------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.48.0(b400f83fe3ac6a1780b7eed419dc4d83dbf32919)
 * Released under the MIT license
 * https://github.com/microsoft/monaco-editor/blob/main/LICENSE.txt
 *-----------------------------------------------------------------------------*/
define("vs/basic-languages/asm/asm", ["require","require"],(require)=>{
"use strict";var moduleExports=(()=>{var s=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var l=(n,e)=>{for(var t in e)s(n,t,{get:e[t],enumerable:!0})},u=(n,e,t,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of i(e))!c.call(n,o)&&o!==t&&s(n,o,{get:()=>e[o],enumerable:!(a=r(e,o))||a.enumerable});return n};var p=n=>u(s({},"__esModule",{value:!0}),n);var d={};l(d,{conf:()=>m,language:()=>g});var m={comments:{lineComment:";"},brackets:[["{","}"],["[","]"],["(",")"]],autoClosingPairs:[{open:"{",close:"}"},{open:"[",close:"]"},{open:"(",close:")"},{open:'"',close:'"'}],surroundingPairs:[{open:"{",close:"}"},{open:"[",close:"]"},{open:"(",close:")"},{open:'"',close:'"'}]},g={defaultToken:"",tokenPostfix:".asm",operators:["@","+","-","*","/","=>"],symbols:/[@*+-\/>=<()]+/,escapes:/\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,tokenizer:{root:[{include:"@label"},{include:"@instruction"},{include:"@command"},{include:"@whitespace"},[/r[0-7]|fr|sp/,"type"],[/[uis]\d+/,"type"],[/[a-z_$][\w]*/i,"identifier"],[/[{}()\[\]]/,"@brackets"],[/[<>](?!@symbols)/,"@brackets"],[/@symbols/,{cases:{"@operators":"operator","@default":""}}],[/\d*\.\d+([eE][\-+]?\d+)?/,"number.float"],[/0[xX][0-9a-fA-F]+/,"number.hex"],[/0[bB][01]+/,"number.bin"],[/0[oO][0-7]+/,"number.oct"],[/\d+/,"number"],[/[;,.]/,"delimiter"],[/"([^"\\]|\\.)*$/,"string.invalid"],[/"/,{token:"string.quote",bracket:"@open",next:"@string"}]],comment:[],string:[[/[^\\"]+/,"string"],[/@escapes/,"string.escape"],[/\\./,"string.escape.invalid"],[/"/,{token:"string.quote",bracket:"@close",next:"@pop"}]],whitespace:[[/[ \t\r\n]+/,"white"],[/;.*$/,"comment"]],label:[[/^\s*[\w.]+\s*:/,"number"]],command:[[/^\s*#[a-zA-Z_][\w]*/,{token:"annotation",log:"annotation token: $0"}]],instruction:[[/^\s*[a-zA-Z_]\w*(\.\w+)?/,{token:"keyword",log:"annotation token: $0"}]]}};return p(d);})();
return moduleExports;
});
