name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Setup
      run: git submodules init && git submodules update
    - name: Build backend
      run: wasm-pack build --target web --reference-types --weak-refs --release --no-pack modules/emulator/backend
    - name: Build mif
      run: wasm-pack build --target web --reference-types --weak-refs --release --no-pack modules/mif
